eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
server:
  port: 8763

spring:
  application:
    name: service-hi2
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1